

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file99choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.junit.runners.Suite;
import signin.SelectLanguage;
import signin.Login;
import signin.SignUp;
import onboarding.CompleteRegistration;
import onboarding.PlacementTest;
import onboarding.Subscription;
import readChapter.CompQuestion;
import readChapter.ReviewChapter;
import readChapter.ReadChapter;
import readChapter.StartLearning;
import readChapter.TestChapter;
import signin.Logout;
import signin.flashCard;




/**
 *
 * @author HP
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
@RunWith(Suite.class)
@Suite.SuiteClasses({
    ClientDriver.class,
    SelectLanguage.class,
    //Login.class,
    //flashCard.class,
  //  Logout.class,
    SignUp.class,
    CompleteRegistration.class, 
    PlacementTest.class,
  // Subscription.class, 
   StartLearning.class,
    ReadChapter.class,
   ReviewChapter.class,
  CompQuestion.class,
    TestChapter.class,
    flashCard.class,
    
    Quit.class,
    
}
)

public class MvnTest {

    @Test
    public void mainTest() {
        System.out.println("MvnTest iStoria is Started ..");
    }

}
