package signin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import static driver.ClientDriver.driver;
import driver.Watcher;
import driver.WebBaseTest;
import io.appium.java_client.TouchAction;
import io.appium.java_client.touch.offset.PointOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import static org.junit.Assert.assertEquals;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Login {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SignUpLayout Delay 1 second applied ");
    }

    //login button
    @Test
    public void test1_Login() {
        //Create new account
        

            String loginXpath = "//android.view.View[@index='2']";
            ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(loginXpath));
            String log = ClientDriver.base.getElementByXpath(loginXpath).getTagName();
            System.out.println("-----------------------" + log);
            ClientDriver.base.getElementByXpath(loginXpath).click();
            
        

            //Create new account
            String loginXpath2 = "//android.view.View[@index='6']";
            ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(loginXpath2));
            String log2 = ClientDriver.base.getElementByXpath(loginXpath2).getTagName();
            System.out.println("---------------------**********--" + log2);
            ClientDriver.base.getElementByXpath(loginXpath2).click();
        
    }

    //SignIn with another account 
    @Test
    public void test2_SignIn_With_Another_Account() {

//       //SignIn with another account 
//       String signInXpath="//android.widget.ImageView[@content-desc=\"Sign In with another account\"]";
//       ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(signInXpath));
//       ClientDriver.base.getElementByXpath(signInXpath).click();
//       
        //Email
        String EmailXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText[1]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(EmailXpath));
        ClientDriver.base.getElementByXpath(EmailXpath).click();
        ClientDriver.base.getElementByXpath(EmailXpath).clear();
        ClientDriver.driver.getKeyboard().sendKeys("qa@qa.com");

        //Password
        String PasswordXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText[2]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(PasswordXpath));
        ClientDriver.base.getElementByXpath(PasswordXpath).click();
        ClientDriver.driver.getKeyboard().sendKeys("123456");

        //Sign in
        String SignInXpath = "//android.widget.Button[@content-desc=\"Sign In\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(SignInXpath));
        ClientDriver.base.getElementByXpath(SignInXpath).click();

    }

    //  @Test
    public void test3_login() {

        //Learn English page
        String welcomeXpath = "//android.widget.ImageView[@content-desc=\"Journey Tab 1 of 4\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(welcomeXpath));
        String learnEnglishExpectedText = ClientDriver.base.getElementByXpath(welcomeXpath).getTagName();
        System.out.println("*****Journey Tab 1 of 4*********" + learnEnglishExpectedText);
        String learnEnglishActual = "Journey Tab 1 of 4";
        System.out.println("--------Journey Tab 1 of 4-----------" + learnEnglishActual);
        assertEquals(learnEnglishExpectedText, learnEnglishActual);
    }

}
