package signin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import static driver.ClientDriver.driver;
import driver.Watcher;
import driver.WebBaseTest;
import io.appium.java_client.TouchAction;
import io.appium.java_client.touch.offset.PointOption;
import static java.lang.System.load;
import java.util.logging.Level;
import java.util.logging.Logger;
import static org.junit.Assert.assertEquals;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import org.openqa.selenium.interactions.touch.TouchActions;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Logout {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Logout.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SignUpLayout Delay 1 second applied ");
    }

    //login button
    @Test
    public void test1_Profile() {
        //Profile tab 
        String profileXpath = "//android.widget.ImageView[@index='3']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(profileXpath));
        ClientDriver.base.getElementByXpath(profileXpath).click();

    }

    @Test
    public void test2_Setting() {
        //Setting tab 

        String settingXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ImageView[2]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(settingXpath));
        ClientDriver.base.getElementByXpath(settingXpath).click();

    }
    
//     @Test
//    public void test3_Scroll_To_LogOut() {
//        
//
//    }

    @Test
    public void test4_Scroll_To_LogOut() {

        //  Screen to scroll
        String screenXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screenXpath));
        ClientDriver.base.getElementByXpath(screenXpath).click();

            TouchAction x = new TouchAction(driver);
            System.out.println("ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt");
         x.press(new PointOption().withCoordinates(0,100)).moveTo(new PointOption().withCoordinates(0,-1000)).perform().release();
        System.out.println("ssssssssssssssssssssssssssssssssssssssssss" + x);
        


    }

    //  @Test
    public void test3_logIn() {

        //Learn English page
        String welcomeXpath = "//android.widget.ImageView[@content-desc=\"Journey Tab 1 of 4\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(welcomeXpath));
        String learnEnglishExpectedText = ClientDriver.base.getElementByXpath(welcomeXpath).getTagName();
        System.out.println("*****Journey Tab 1 of 4*********" + learnEnglishExpectedText);
        String learnEnglishActual = "Journey Tab 1 of 4";
        System.out.println("--------Journey Tab 1 of 4-----------" + learnEnglishActual);
        assertEquals(learnEnglishExpectedText, learnEnglishActual);
    }

}
