package signin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import static driver.ClientDriver.driver;
import driver.Watcher;
import driver.WebBaseTest;
import io.appium.java_client.TouchAction;
import io.appium.java_client.touch.offset.PointOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import static org.junit.Assert.assertEquals;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class SignUp {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SignUpLayout Delay 1 second applied ");
    }

    @Test
    public void test1_SingUp() {
        //Create new account
        String getStartedXpath = "//android.widget.Button[@content-desc=\"GET STARTED\"]";
        System.out.println("Get Started");
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(getStartedXpath));
        ClientDriver.base.getElementByXpath(getStartedXpath).click();
    }
      
    @Test
    public  void test2_Complete_Register(){
                
       //Full name
       String FullNameXpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.widget.EditText[1]";
       ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(FullNameXpath));
       ClientDriver.base.getElementByXpath(FullNameXpath).click();
       ClientDriver.driver.getKeyboard().sendKeys("Automation");
       //Age
       String AgeXpath="//android.view.View[@content-desc=\"Age\"]";
       ClientDriver.base.getElementByXpath(AgeXpath).click();
       String popUpAgeXpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View[1]/android.view.View";
       ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(popUpAgeXpath));
       String doneButtonXpath="//android.widget.Button[@content-desc=\"Done\"]";
       ClientDriver.base.getElementByXpath(doneButtonXpath).click();
       //Gender
      String genderXpath="//android.view.View[@content-desc=\"Female\"]";
      ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(genderXpath));
      ClientDriver.base.getElementByXpath(genderXpath).click();
      //Email
      String emailXpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.widget.EditText[2]";
       ClientDriver.base.getElementByXpath(emailXpath).click();
       String random=WebBaseTest.generateRandomEmail(15);
         ClientDriver.driver.getKeyboard().sendKeys(random);

       //Password
       String passwordXpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.widget.EditText[3]";
       ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(passwordXpath));
       ClientDriver.base.getElementByXpath(passwordXpath).click();
       ClientDriver.driver.getKeyboard().sendKeys("123456");
       
       //Password
       String signUpXpath="//android.widget.Button[@content-desc=\"Sign Up\"]";
       ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(signUpXpath));
       ClientDriver.base.getElementByXpath(signUpXpath).click();
      
//        TouchAction x = new TouchAction(driver);
//         x.press(new PointOption().withCoordinates(52, 1356)).moveTo(new PointOption().withCoordinates(620, 449)).perform().release();
//         System.out.println("ssssssssssssssssssssssssssssssssssssssssss"+x);
     
    }
    @Test
    public void test3_Create_account(){
     
       //Learn English page
       String welcomeXpath="//android.view.View[@content-desc=\"Welcome!\"]";
       ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(welcomeXpath));
       String welcomScreen = ClientDriver.base.getElementByXpath(welcomeXpath).getTagName();      
        System.out.println("*****Welcome*********"+welcomScreen); 
        String learnEnglishActual="Welcome!";
        System.out.println("--------Welcome-----------"+learnEnglishActual);    
        assertEquals(welcomScreen, learnEnglishActual);
    }
    
}


