package readChapter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import static driver.ClientDriver.driver;
import driver.Watcher;
import io.appium.java_client.TouchAction;
import static io.appium.java_client.touch.offset.ElementOption.element;
import io.appium.java_client.touch.offset.PointOption;
import static io.appium.java_client.touch.offset.PointOption.point;
import java.util.logging.Level;
import java.util.logging.Logger;
import static org.junit.Assert.assertEquals;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import static org.openqa.selenium.By.id;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.Point;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.interactions.touch.TouchActions;
import signin.SignUp;
import javax.swing.JScrollPane;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class ReadChapter {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(1500);
        } catch (InterruptedException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SignUpLayout Delay 10 seconds applied ");
    }

    
//    @Test
//    public void test2_startReading() {
//
//        String rotatePopUpXpath = "//android.view.View[@content-desc=\"Try it now\"]";
//        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(rotatePopUpXpath));
//        ClientDriver.base.getElementByXpath(rotatePopUpXpath).click();
//    }

    
    @Test
    public void test1_startReading() {
        
        // chapter screen
        String storyXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(storyXpath));
        ClientDriver.base.getElementByXpath(storyXpath).click();
 
        // Click to the word
        String clickToWordXpath = "//android.view.View[@index='10']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(clickToWordXpath));
        ClientDriver.base.getElementByXpath(clickToWordXpath).click();

        // Tips
        String closeTipXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View[2]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(closeTipXpath));
        ClientDriver.base.getElementByXpath(closeTipXpath).click();
        ClientDriver.base.getElementByXpath(closeTipXpath).click();
        ClientDriver.base.getElementByXpath(closeTipXpath).click();

        // Move to learn
        String wordToLearnXpath = "//android.widget.Button[@content-desc=\"Learning\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(wordToLearnXpath));
        ClientDriver.base.getElementByXpath(wordToLearnXpath).click();

        //Chapter screen
        String storyXpath2 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.ScrollView/android.view.View/android.view.View/android.view.View/android.view.View[3]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(storyXpath2));
        ClientDriver.base.getElementByXpath(storyXpath2).click();
       
        //Click to the word
        String clickToWord2Xpath = "//android.view.View[@index='19']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(clickToWord2Xpath));
        ClientDriver.base.getElementByXpath(clickToWord2Xpath).click();

        //Moe to know
        String wordToKnowXpath = "//android.widget.Button[@content-desc=\"I know\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(wordToKnowXpath));
        ClientDriver.base.getElementByXpath(wordToKnowXpath).click();
                
    }
    
        @Test
    public void test2_listen_chapter() {
        
        //Click to screen
        String screen = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.view.View/android.view.View/android.view.View/android.view.View[3]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen));

        //Click to listen to Assisstante button
        String listenAssistante = "//android.widget.ImageView[@content-desc=\"Listen to assistant\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(listenAssistante));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(listenAssistante));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(listenAssistante));
        ClientDriver.base.getElementByXpath(listenAssistante).click();

        // Increase speed
        String speed = "//android.view.View[@content-desc=\"1.0x\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(speed));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(speed));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(speed));
        ClientDriver.base.getElementByXpath(speed).click();

        //Click to play button
        String playSound = "//android.view.View[@index='37']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(playSound));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(playSound));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(playSound));
        ClientDriver.base.getElementByXpath(playSound).click();
        String s = ClientDriver.base.getElementByXpath(playSound).getTagName();
        System.out.println("0000" + "/n" + s);

        //Pause the chapter audio
        String stopSound ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ImageView";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(stopSound));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(stopSound));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(stopSound));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(stopSound));
        ClientDriver.base.getElementByXpath(stopSound).click();

        //Click to forward button
        String forward = "//android.widget.ImageView[@content-desc=\"Forward\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(forward));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(forward));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(forward));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(forward));
        for (int i = 0; i < 44; i++) {
         ClientDriver.base.getElementByXpath(forward).click();
        }
        //Play the sound to make scroll
        String play2 = "//android.view.View[@index='37']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(play2));
        ClientDriver.base.getElementByXpath(play2).click();
        ClientDriver.base.Wait(3);
        
        // Finish reading the story
        String finshReading = "//android.view.View[@content-desc=\"Finish Reading\"]";       
                  ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(finshReading));            
                ClientDriver.base.getElementByXpath(finshReading).click();
        ClientDriver.base.Wait(10);

        
        }      


    @Test
    public void test5_checkTestResult() {
     //Check test result
        String expectedResultXpath = "//android.widget.ImageView[@content-desc=\"Back to chapter\"]";
         ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(expectedResultXpath));
        String expectedResult = ClientDriver.base.getElementByXpath(expectedResultXpath).getTagName();
       System.out.println("-----------------" + expectedResult);
        String actualResult = "Back to chapter";
        System.out.println("*****************" + actualResult);
        assertEquals(expectedResult, actualResult);
}

      }
