package readChapter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import static driver.ClientDriver.driver;
import driver.Watcher;
import io.appium.java_client.TouchAction;
import static io.appium.java_client.touch.offset.ElementOption.element;
import io.appium.java_client.touch.offset.PointOption;
import static io.appium.java_client.touch.offset.PointOption.point;
import java.util.logging.Level;
import java.util.logging.Logger;
import static org.junit.Assert.assertEquals;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import static org.openqa.selenium.By.id;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.Point;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.interactions.touch.TouchActions;
import signin.SignUp;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class ReviewChapter {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(1500);
        } catch (InterruptedException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SignUpLayout Delay 10 seconds applied ");
    }

    @Test
    public void test1_reviewChapter() {
       
        //Favourite words
        String favouriteLearnWord ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[9]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.view.View";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(favouriteLearnWord));
        ClientDriver.base.getElementByXpath(favouriteLearnWord).click();
        
        //Know tab
        String knowTab = "//android.view.View[@content-desc=\"I know Tab 2 of 2\"]";
        ClientDriver.base.getElementByXpath(favouriteLearnWord).click();
                
    }
    
    
     @Test
    public void test2_finishReview() {
        //finish review       
         String startTest = "//android.widget.Button[@content-desc=\"Start your test\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(startTest));
        ClientDriver.base.getElementByXpath(startTest).click();     
    }


    //@Test
       public void test2_checkTestResult() {
      //Check test result
         String expectedResultXpath = "//android.view.View[@content-desc=\" Question 1 \"]";
         ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(expectedResultXpath));
        String expectedResult = ClientDriver.base.getElementByXpath(expectedResultXpath).getTagName();
        System.out.println("-----------------" + expectedResult);
        String actualResult = "Question 1";
        System.out.println("*****************" + actualResult);
        assertEquals(expectedResult, actualResult);
}
}

