package readChapter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import static driver.ClientDriver.driver;
import driver.Watcher;
import io.appium.java_client.TouchAction;
import static io.appium.java_client.touch.offset.ElementOption.element;
import io.appium.java_client.touch.offset.PointOption;
import static io.appium.java_client.touch.offset.PointOption.point;
import java.util.logging.Level;
import java.util.logging.Logger;
import static org.junit.Assert.assertEquals;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import static org.openqa.selenium.By.id;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.Point;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.interactions.touch.TouchActions;
import signin.SignUp;
import javax.swing.JScrollPane;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class scrollAtTheStory {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(1500);
        } catch (InterruptedException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SignUpLayout Delay 10 seconds applied ");
    }

    @Test
    public void test1_startReadChapter() {
        //Select story 
        String selectStoryXpath = "//android.widget.ImageView[@index='1']";
        String x1 = ClientDriver.base.getElementByXpath(selectStoryXpath).getTagName();
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(selectStoryXpath));
        ClientDriver.base.getElementByXpath(selectStoryXpath).click();

        //Read chapter
        String readChapterXpath = "//android.widget.ImageView[@content-desc=\"Read Chapter\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(readChapterXpath));
        ClientDriver.base.getElementByXpath(readChapterXpath).click();

        //Read chapter new words
        String newWordsXpath = "//android.widget.Button[@content-desc=\"Read Chapter\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(newWordsXpath));
        ClientDriver.base.getElementByXpath(newWordsXpath).click();

//Read chapter
//        String readChapter2Xpath = "//android.widget.Button[@content-desc=\"Read Chapter\"]";
//        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(readChapter2Xpath));
//        ClientDriver.base.getElementByXpath(readChapter2Xpath).click();
//        for (int i = 0; i < 2; i++) {
//            //Know words
//            String knowWordXpath;
//            if (i % 2 == 1) {
//                knowWordXpath = "(//android.view.View[@content-desc=\"Know\"])";
//
//            } else {
//                knowWordXpath = "//android.view.View[@content-desc=\"Learn\"]";
//
//            }
//            ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(knowWordXpath));
//            ClientDriver.base.getElementByXpath(knowWordXpath).click();
//        }
    }

    @Test
    public void test2_startReading() {

        String rotatePopUpXpath = "//android.view.View[@content-desc=\"Try it now\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(rotatePopUpXpath));
        ClientDriver.base.getElementByXpath(rotatePopUpXpath).click();
    }

    @Test
    public void test3_listen_chapter() {
        String screen = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.view.View/android.view.View/android.view.View/android.view.View[3]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen));

        String listenAssistante = "//android.widget.ImageView[@content-desc=\"Listen to assistant\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(listenAssistante));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(listenAssistante));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(listenAssistante));
        ClientDriver.base.getElementByXpath(listenAssistante).click();

//    String playSound2="00000000-0000-0304-0000-017f00000004";
//
//  //   ClientDriver.base.waitForElementToBeClickableBy(By.id(playSound2));
//    ClientDriver.base.getElementById(playSound2).click();
//android.widget.ImageButton[@content-desc="Play"]
        String speed = "//android.view.View[@content-desc=\"1.0x\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(speed));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(speed));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(speed));
        ClientDriver.base.getElementByXpath(speed).click();

        String play1 = "//android.view.View[@index='33']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(play1));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(play1));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(play1));
        ClientDriver.base.getElementByXpath(play1).click();
        String s = ClientDriver.base.getElementByXpath(play1).getTagName();
        System.out.println("sssssssssssssssssssssssssssssssssss00000000000000000000000000000000000000" + "/n" + s);

        String stopSound = "//android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ImageView";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(stopSound));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(stopSound));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(stopSound));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(stopSound));

        ClientDriver.base.getElementByXpath(stopSound).click();

        //listen
        String forward = "//android.widget.ImageView[@content-desc=\"Forward\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(forward));

        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(forward));
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(forward));

        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(forward));
        for (int i = 0; i < 40; i++) {
         ClientDriver.base.getElementByXpath(forward).click();

        }
        String play2 = "//android.view.View[@index='33']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(play2));
        ClientDriver.base.getElementByXpath(play2).click();
        

        String finshReading = "//android.view.View[@content-desc=\"Finish Reading\"]";
        for (int i = 0; i < 20; i++) {
                  ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(finshReading));
        }
      
        ClientDriver.base.getElementByXpath(finshReading).click();

    }

    // @Test
    public void test3_scroll() {

        String screen = "/hierarchy/android.widget.FrameLayout";

        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen));
//        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen));
//        ClientDriver.base.getElementByXpath(screen).click();
        TouchAction move2 = new TouchAction(driver);
        move2.press(new PointOption().withCoordinates(11, 93)).moveTo(new PointOption().withCoordinates(1069, 2177)).release().perform();

        //
        String screen1 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen1));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen1));
        ClientDriver.base.getElementByXpath(screen1).click();
        TouchAction move3 = new TouchAction(driver);
        move3.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();

        //
        String screen2 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen2));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen2));
        ClientDriver.base.getElementByXpath(screen2).click();
        TouchAction move4 = new TouchAction(driver);
        move4.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();

        //
        String screen5 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen5));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen5));
        ClientDriver.base.getElementByXpath(screen5).click();
        TouchAction move5 = new TouchAction(driver);
        move5.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();

        //
        String screen6 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen6));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen6));
        ClientDriver.base.getElementByXpath(screen6).click();
        TouchAction move6 = new TouchAction(driver);
        move6.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();

        //
        String screen7 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen7));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen7));
        ClientDriver.base.getElementByXpath(screen7).click();
        TouchAction move7 = new TouchAction(driver);
        move7.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();

        //
        String screen8 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen8));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen8));
        ClientDriver.base.getElementByXpath(screen8).click();
        TouchAction move8 = new TouchAction(driver);
        move8.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();
//
        String screen9 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen9));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen9));
        ClientDriver.base.getElementByXpath(screen9).click();
        TouchAction move9 = new TouchAction(driver);
        move9.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();

        //
        String screen10 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen10));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen10));
        ClientDriver.base.getElementByXpath(screen10).click();
        TouchAction move10 = new TouchAction(driver);
        move10.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();
//
        String screen11 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen11));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen11));
        ClientDriver.base.getElementByXpath(screen11).click();
        TouchAction move11 = new TouchAction(driver);
        move11.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();

        //
        String screen12 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen12));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen12));
        ClientDriver.base.getElementByXpath(screen12).click();
        TouchAction move12 = new TouchAction(driver);
        move12.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();
//
        String screen13 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen13));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen13));
        ClientDriver.base.getElementByXpath(screen13).click();
        TouchAction move13 = new TouchAction(driver);
        move13.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();
//
        String screen14 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.view.View/android.view.View/android.view.View/android.view.View[3]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen14));
        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen14));
        ClientDriver.base.getElementByXpath(screen14).click();
        TouchAction move14 = new TouchAction(driver);
        move14.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();

        WebElement storyElement = driver.findElement(By.xpath("//android.view.View[@content-desc=\"my food\"]"));
        JavascriptExecutor jsExecutor = (JavascriptExecutor) driver;
        jsExecutor.executeScript("arguments[0].scrollIntoView(true);", storyElement);
        String storyText = storyElement.getText();
        System.out.println(storyText);

//
// String screen15 = "";
//        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen15));
//        ClientDriver.base.waitForElementToBeClickableBy(By.xpath(screen15));
//        ClientDriver.base.getElementByXpath(screen15).click();
//        TouchAction move15 = new TouchAction(driver);
//        move15.press(new PointOption().withCoordinates(7, 1988)).moveTo(new PointOption().withCoordinates(1048, 547)).release().perform();
        String clickToWordXpath = "//android.view.View[@index='9']";
        String clickToWord = ClientDriver.base.getElementByXpath(clickToWordXpath).getTagName();
        System.out.println("------------------------" + clickToWord);
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(clickToWordXpath));
        ClientDriver.base.getElementByXpath(clickToWordXpath).click();
    }

    //@Test
    public void test3_startReading() {

        String storyXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ScrollView";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(storyXpath));
        ClientDriver.base.getElementByXpath(storyXpath).click();

        String clickToWordXpath = "//android.view.View[@index='9']";
        String clickToWord = ClientDriver.base.getElementByXpath(clickToWordXpath).getTagName();
        System.out.println("------------------------" + clickToWord);
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(clickToWordXpath));
        ClientDriver.base.getElementByXpath(clickToWordXpath).click();

        String closeTipXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View[2]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(closeTipXpath));
        ClientDriver.base.getElementByXpath(closeTipXpath).click();
        ClientDriver.base.getElementByXpath(closeTipXpath).click();
        ClientDriver.base.getElementByXpath(closeTipXpath).click();

        String wordToLearnXpath = "//android.widget.Button[@content-desc=\"Learning\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(wordToLearnXpath));
        ClientDriver.base.getElementByXpath(wordToLearnXpath).click();

        String storyXpath2 = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.ScrollView/android.view.View/android.view.View/android.view.View/android.view.View[3]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(storyXpath2));
        ClientDriver.base.getElementByXpath(storyXpath2).click();

        String clickToWord2Xpath = "//android.view.View[@index='13']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(clickToWord2Xpath));
        ClientDriver.base.getElementByXpath(clickToWord2Xpath).click();

        String wordToKnowXpath = "//android.widget.Button[@content-desc=\"I know\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(wordToKnowXpath));
        ClientDriver.base.getElementByXpath(wordToKnowXpath).click();
        System.out.println("wordToKnowXpath");

        TouchAction x = new TouchAction(driver);
        x.press(new PointOption().withCoordinates(53, 2069)).moveTo(new PointOption().withCoordinates(940, 568)).release().perform();
        System.out.println("scroooooooooooooooooooooooooooooolllllllll222222222222" + x);

        String clickToWord3Xpath = "//android.view.View[@index='35']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(clickToWord3Xpath));
        ClientDriver.base.getElementByXpath(clickToWord3Xpath).click();

        String wordToKnow2Xpath = "//android.widget.Button[@content-desc=\"I know\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(wordToKnow2Xpath));
        ClientDriver.base.getElementByXpath(wordToKnow2Xpath).click();
        System.out.println("wordToKnowXpath");
//
//        String screen = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View";
//        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen));
//        ClientDriver.base.getElementByXpath(screen).click();
//       String m= ClientDriver.base.getElementByXpath(screen).getText();
//               String m2= ClientDriver.base.getElementByXpath(screen).getTagName();
//        System.out.println("3333333333333333"+m);
//        System.out.println("3333333333333333"+m2);
//
//        TouchAction x = new TouchAction(driver);
//        
//       
//        x.press(new PointOption().withCoordinates(48, 1378)).moveTo(new PointOption().withCoordinates(604, 396)).release().perform();
//        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen));
//        ClientDriver.base.getElementByXpath(screen).click();
//        x.press(new PointOption().withCoordinates(48, 1378)).moveTo(new PointOption().withCoordinates(604, 396)).release().perform();
//         ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(screen));
//        ClientDriver.base.getElementByXpath(screen).click();
//        x.press(new PointOption().withCoordinates(48, 1378)).moveTo(new PointOption().withCoordinates(604, 396)).release().perform();
//
//        System.out.println("ssssssssssssssssssssssssssssssssssssssssss" + x);
////
//        String finishReadingXpath = "//android.view.View[@content-desc=\"Finish Reading\"]";
//        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(finishReadingXpath));
//        ClientDriver.base.getElementByXpath(finishReadingXpath).click();

//            String clickToWord3Xpath = "//android.view.View[@content-desc=\"Finish Reading\"]";
//
//            ClientDriver.base.scrollDownToElement(clickToWord3Xpath);
//
//        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(clickToWord3Xpath));
//        ClientDriver.base.getElementByXpath(clickToWord3Xpath).click();
    }

}

//    @Test
//       public void test2_checkTestResult() {
//      //Check test result
//         String expectedResultXpath = "//android.view.View[@content-desc=\"Level 1\"]";
//         ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(expectedResultXpath));
//        String expectedResult = ClientDriver.base.getElementByXpath(expectedResultXpath).getTagName();
//        System.out.println("-----------------" + expectedResult);
//        String actualResult = "Level";
//        System.out.println("*****************" + actualResult);
//        assertEquals(expectedResult, actualResult);
//}

     //   }
