package readChapter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import static driver.ClientDriver.driver;
import driver.Watcher;
import io.appium.java_client.TouchAction;
import static io.appium.java_client.touch.offset.ElementOption.element;
import io.appium.java_client.touch.offset.PointOption;
import static io.appium.java_client.touch.offset.PointOption.point;
import java.util.logging.Level;
import java.util.logging.Logger;
import static org.junit.Assert.assertEquals;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import static org.openqa.selenium.By.id;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.Point;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.interactions.touch.TouchActions;
import signin.SignUp;
import javax.swing.JScrollPane;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class StartLearning {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SignUpLayout Delay 10 seconds applied ");
    }

    @Test
    public void test1_startReadChapter() {
//        //home
        String homeXpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[4]/android.view.View/android.view.View";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(homeXpath));
        ClientDriver.base.getElementByXpath(homeXpath).click();
        
        //Select story 
        String selectStoryXpath = "//android.widget.ImageView[@index='0']";
        String x1 = ClientDriver.base.getElementByXpath(selectStoryXpath).getTagName();
        System.out.println("------------------------------- "+ x1);
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(selectStoryXpath));
        ClientDriver.base.getElementByXpath(selectStoryXpath).click();        
    }
    
     @Test
    public void test2_startLearning() {        
         //Start Learning
        String startLearningXpath ="//android.widget.ImageView[@index='0']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(startLearningXpath));
        ClientDriver.base.getElementByXpath(startLearningXpath).click();
        
        String startLearning2Xpath ="//android.widget.ImageView[@content-desc=\"Start learning\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(startLearning2Xpath));
        ClientDriver.base.getElementByXpath(startLearning2Xpath).click();
    }
    

  //  @Test
    public void test3_wordStatus() {
        //move the word to learn
        String learnXpath = "(//android.widget.Button[@content-desc=\"Learning\"])[1]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(learnXpath));
        ClientDriver.base.getElementByXpath(learnXpath).click();
        
         String learn2Xpath = "(//android.widget.Button[@index='0']";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(learn2Xpath));
        ClientDriver.base.getElementByXpath(learn2Xpath).click();
        
        
        //Moe all to know
        String knowXpath = "//android.widget.ImageView[@content-desc=\"All to 'Know'\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(knowXpath));
        ClientDriver.base.getElementByXpath(knowXpath).click();

    }
    
    // @Test  // check the number at progress
    public void test3_Summery(){
        
    }
    
     @Test 
    public void test4_readChapter(){
        String readXpath="//android.widget.ImageView[@content-desc=\"Read Chapter\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(readXpath));
        ClientDriver.base.getElementByXpath(readXpath).click();
    }

  //  @Test
    public void test5_checkTestResult() {
        //Check test result
        String expectedResultXpath = "//android.view.View[@content-desc=\"The Town Mouse and the Country Mouse\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(expectedResultXpath));
        String expectedResult = ClientDriver.base.getElementByXpath(expectedResultXpath).getTagName();
        System.out.println("-----------------" + expectedResult);
        String actualResult = "The Town Mouse and the Country Mouse";
        System.out.println("*****************" + actualResult);
        assertEquals(expectedResult, actualResult);
    }
}
