package onboarding;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
// Generated by Selenium IDE
import driver.ClientDriver;
import driver.Watcher;
import java.util.logging.Level;
import java.util.logging.Logger;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.internal.WebElementToJsonConverter;
import signin.SignUp;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class CompleteRegistration {

    String testCaseId;
    String testRunId = "62";//Signin -Automated test cases
    @Rule
    public Watcher watcher = new Watcher(ClientDriver.driver);

    @BeforeClass
    public static void delay() {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("SignUpLayout Delay 10 seconds applied ");
    }
    
      @Test
    //welcome screen 
    public void test1_Welcome() {
        String continueXpath="//android.widget.Button[@content-desc=\"Continue\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(continueXpath));
        ClientDriver.base.getElementByXpath(continueXpath).click();
    }

    @Test
    //Select learn English reason
    public void test2_Learn_English_reason() {
        //Selec Expand my job opportunities
        String selectReason1Xpath = "//android.widget.ImageView[@content-desc=\"Expand my job opportunities\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(selectReason1Xpath));
        ClientDriver.base.getElementByXpath(selectReason1Xpath).click();

      
        //Continue buttton
        String contnueXpath = "//android.widget.Button[@content-desc=\"Continue\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(contnueXpath));
        ClientDriver.base.getElementByXpath(contnueXpath).click();
    }

    @Test
    public void test3_checkTestResult() {
        //Check test result
        String expectedResultXpath = "//android.view.View[@content-desc=\"Placement test\"]";
        ClientDriver.base.waitForElementToBeVisibleBy(By.xpath(expectedResultXpath));
        String expectedResult = ClientDriver.base.getElementByXpath(expectedResultXpath).getTagName();
        System.out.println("-----------------" + expectedResult);
        String actualResult = "Placement test";
        System.out.println("*****************" + actualResult);
        assertEquals(expectedResult, actualResult);
        
    }
}
